version: 1.0.{build}
configuration: Release
nuget:
  account_feed: true
  project_feed: true
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key: 820689db-908b-4ad2-b25e-c3237095f4ea
    secure: ubOtyPLGDRR2As2YTkLUUN8cjmV66GWheJaDWf52o133MIi4Qe3nw0pUDjBkQCA2
  skip_symbols: false
  artifact: /.*\.nupkg/
notifications:
- provider: Email
  to:
  - reinaldo@enkilabs.com.br
  subject: enki.common AppVeyor build Fail
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false